---
#apiVersion: kustomize.config.k8s.io/v1beta1
apiVersion: kustomize.config.k8s.io/v1alpha2
kind: Kustomization
namespace: terraform-01
resources:
- rbac.yaml
- secretproviderclass.yaml
- setup.yaml
