apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  terraform.tfvars: c3Vic2NyaXB0aW9uX2lkICAgPSAiZDEzOGMzNDQtYzY1Yi00ZTAxLWI4YWQtOWFkZmIxZGFjYWM0Ig0KdGVuYW50X2lkICAgICAgICAgPSAiYTlhOGUzNzUtZmFjMS00ZWMyLTgyMGEtY2ZiNmViNWNmMDFiIg0KY2xpZW50X2lkICAgICAgICAgPSAiYWU5MDFkY2ItNzBkMS00N2ZmLThiMGEtNjZjZGI3ZTU2MjI5Ig0KY2xpZW50X3NlY3JldCAgICAgPSAiZjFWOFF+VEdmSFB2NTZaZ3FJRUFzV0xpb2x6RlY2VGFOZmxtSGE5biI=
