---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/vmfernandezg/tf-controller-helloworld
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  approvePlan: "plan-main@sha1:af69972b7f3098e801a6e4de15e12b5965826f35"
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  writeOutputsToSecret:
    name: helloworld-outputs
