---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/vmfernandezg/tf-controller-helloworld
  ref:
    branch: test
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  approvePlan: ""
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  varsFrom:
  - kind: Secret
    name: mysecret
